version: '3'
services:
  db:
    container_name: moto-alerts-postgres
    # image: ghcr.io/baosystems/postgis:latest
    # image: ghcr.io/baosystems/postgis:latest <-- Raspberry Pi 
    image: imresamu/postgis:17-3.5.2-alpine3.21
    # image: imresamu/postgis:17-3.5.2-alpine3.21 <-- MacOS M-chip
    environment:
      POSTGRES_DB: moto_alerts_local
      # POSTGRES_DB: moto_alerts_production
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgis/data
    restart: always

volumes:
  pgdata:
