AUTH:
  UPDATE_LAST_AUTH_EVERY_MS: 10000

GENERAL:
  ENV: "local"
  PORT: 8080
  WS_PORT: 3001

DATABASE:
  HOST: "localhost"
  PORT: 5432
  USER: "user"
  DATABASE: "moto_alerts_local"

MAP_IMAGES_GENERATION:
  ZOOM: 18
  MARKER_X: 275
  MARKER_Y: 175

LOGS:
  WS_LOGS_ENABLED: FALSE

ACCIDENT:
  RADIUS_KM: 5000
  EXPIRE_INACTIVE_ACCIDENTS:
    INACTIVE_FOR_MS: 3600000
    CRON: "* * * * *"
    CRON_ENABLED: TRUE

NOTIFICATIONS:
  EXPO_PUSH_NOTIFICATION_URL: "https://exp.host/--/api/v2/push/send"
